services:
  # Using confluentinc docker images: https://hub.docker.com/r/confluentinc/cp-kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:7.9.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # Only use 1 broker because don't need data replication or high availability in local development
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
