spring:
  kafka: # See the list of Spring Kafka properties at: https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.integration.spring.kafka.producer.bootstrap-servers
    bootstrap-servers: localhost:9092 # The port where my Kafka broker is running (via Docker containers)
    template:
      default-topic: order-tracking-topic # The topic name
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group # All consumers with the same group ID share messages
      auto-offset-reset: earliest # Consume from the beginning of the topic
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.example.ordertrackingsystem.model.Order # Tells Spring what class to deserialize into (b/c we're not using our own custom typed ObjectMapper)
